server:
  port: :32081

tushare:
  url: http://api.tushare.pro
  token: 48664f289b98d05be6737d086fd711ca62f7ba08d17410a73cfa8181

proxy:
  url: http://127.0.0.1:5010
  
mysql:
  url: dss:yYzJmeL73FjG3KB4@tcp(ubuntu:3306)/dss?parseTime=True&loc=Local
  database: dss

neo4j:
  url: bolt://ubuntu:7687
  database: neo4j
  username: neo4j
  password: DSSneo4j