version: '3'
services:
  dss-data:
    image: registry.cn-hangzhou.aliyuncs.com/dss-pod/dss-data:v1.1.7
    container_name: dss-data
    ports:
      - "32081:8081"
    environment:
      TUSHARE_URL: "http://api.tushare.pro"
      TUSHARE_TOKEN: "48664f289b98d05be6737d086fd711ca62f7ba08d17410a73cfa8181"
      PROXY_URL: "http://172.17.0.3:5010"
      MYSQL_URL: "dss:yYzJmeL73FjG3KB4@tcp(172.17.0.1:3306)/dss?parseTime=True&loc=Local"
      MYSQL_DATABASE: dss
    restart: always
    network_mode: bridge
