version: '3'
services:
  dss-data:
    image: registry.cn-hangzhou.aliyuncs.com/dss-pod/dss-data:v1.0.4
    container_name: dss-data
    ports:
      - "32081:8081"
    environment:
      TUSHARE_TOKEN: "48664f289b98d05be6737d086fd711ca62f7ba08d17410a73cfa8181"
      PROXY_URL: "http://172.17.0.1:5010"
      MYSQL_HOST: "172.17.0.1"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "dss"
      MYSQL_USERNAME: "dss"
      MYSQL_PASSWORD: "yYzJmeL73FjG3KB4"
    restart: always
    network_mode: bridge
