version: '3'
networks:
   default:
    name: default-net
services:
  dss-data:
    build: .
    container_name: dss-data
    ports:
      - "32081:32081"
    deploy:
        resources:
            limits:
              memory: 2G
            reservations:
              memory: 256M
    environment:
      GIN_MODE: "release"
      TUSHARE_URL: "http://api.tushare.pro"
      TUSHARE_TOKEN: "48664f289b98d05be6737d086fd711ca62f7ba08d17410a73cfa8181"
      MYSQL_URL: "dss:yYzJmeL73FjG3KB4@tcp(172.18.0.1:3306)/dss?parseTime=True&loc=Local"
      MYSQL_DATABASE: dss
      NEO4J_URL: bolt://172.18.0.4:7687
      NEO4J_DATABASE: neo4j
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: DSSneo4j
    restart: always
    network_mode: bridge
    networks:
      default:
        ipv4_address: 172.18.0.11