DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8
Other:
  Addr: :8081

tushare:
  url: http://api.tushare.pro
  token: ${TUSHARE_TOKEN}

proxy:
  url: ${PROXY_URL}

mysql:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  database: ${MYSQL_DATABASE}
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
