server:
  port: :8081

tushare:
  url: http://api.tushare.pro
  token: 48664f289b98d05be6737d086fd711ca62f7ba08d17410a73cfa8181

proxy:
  url: http://127.0.0.1:5010
  
mysql:
  url: dss_test:hxHazFWeKaLtw5zc@tcp(127.0.0.1:3306)/dss_test?parseTime=True&loc=Local
  database: dss_test