DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8
Other:
  Addr: :8081

tushare:
  url: http://api.tushare.pro
  token: 48664f289b98d05be6737d086fd711ca62f7ba08d17410a73cfa8181

proxy:
  url: http://172.17.0.1:5010

mysql:
  url: dss:yYzJmeL73FjG3KB4@tcp(172.17.0.1:3306)/dss?parseTime=True&loc=Local
  database: dss